version: "3"
services:
  auth-db: 
    image: postgres:11
    container_name: auth-db
    restart: always
    networks:
      - sales-network
    healthcheck:
      test: exit 0
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - 5432:5432

  product-db: 
    image: postgres:11
    container_name: product-db
    restart: always
    networks:
      - sales-network
    healthcheck:
      test: exit 0
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - 5433:5432
      
  sales-db: 
    image: tutum/mongodb
    container_name: sales-db
    restart: always
    networks:
      - sales-network
    healthcheck:
      test: exit 0
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - MONGODB_USER=admin
      - MONGODB_DATABASE=sales
      - MONGODB_PASS=123456
    ports: 
      - 27017:27017
      - 28017:28017

  sales_rabbit: 
    image: rabbitmq:3-management
    container_name: sales_rabbit
    hostname: sales_rabbit
    networks:
      - sales-network
    healthcheck:
      test: exit 0
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports: 
      - 5672:5672
      - 27676:27676
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  auth-api: 
    build: './auth-api'
    container_name: auth-api
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - sales-network
    environment:
      - PORT=8080
      - API_SECRET=dGVzdGUxc2Q2YTUxZjU2YXNkZjE1NnNhM3NkMWY2YXNhYQ==
      - DB_HOST=auth-db
      - DB_NAME=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - NODE_ENV=container
    ports: 
      - 8080:8080

  product-api: 
    build: './product-api'
    container_name: product-api
    depends_on:
      product-db:
        condition: service_healthy
      sales_rabbit:
        condition: service_healthy
    networks:
      - sales-network
    environment:
      - PORT=8081
      - API_SECRET=dGVzdGUxc2Q2YTUxZjU2YXNkZjE1NnNhM3NkMWY2YXNhYQ==
      - DB_HOST=product-db
      - DB_NAME=product-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - RABBIT_MQ_HOST=sales_rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - SALES_HOST=sales-api
      - SALES_PORT=8082
    ports: 
      - 8081:8081

  sales-api: 
    build: './sales-api'
    container_name: sales-api
    depends_on:
      sales-db:
        condition: service_healthy
      sales_rabbit:
        condition: service_healthy
    networks:
      - sales-network
    environment:
      - PORT=8082
      - API_SECRET=dGVzdGUxc2Q2YTUxZjU2YXNkZjE1NnNhM3NkMWY2YXNhYQ==
      - MONGO_DB_URL=mongodb://admin:123456@sales-db:27017/sales
      - RABBIT_MQ_URL=amqp://sales_rabbit:5672
      - PRODUCT_API_URL=http://product-api:8081/api/product
      - NODE_ENV=container
    ports: 
      - 8082:8082

networks:
  sales-network:
    driver: bridge