server:
  port : ${PORT:8081}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: postgres
    password: postgres
    initialization-mode: always
    continue-on-error: true
    platform: postgresql
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  spring:
    main:
      allow-circular-references: true

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

app-config:

  services:
    sales: http://${SALES_HOST:localhost}:${SALES_PORT:8082}

  secrets:
    api-secret: ${API_SECRET:VGVzdHNlMTYxNjUxNTYxNTYxNjYxNUFTRVJFQURGREFERkRBRkVBREZBZA==}

  rabbit:
    exchange:
      product: product.topic

    routing-key:
      product-stock: product-stock-update.routing-key
      sales-confirmation: sales-confirmation.routing-key

    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue